# Generated by Django 4.2.7 on 2023-11-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('codigo_integracao', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('logradouro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email_contato', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('data_ingresso', models.DateField()),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cidade', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoa', to='core.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoa_empresa', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departamento', to='core.empresa'),
        ),
    ]
